# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  check-java-maven:
    name: "Ensure that Java and Maven are installed."
    runs-on: self-hosted
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: "Ensure that Maven is installed"
        run: |
          if ! command -v mvn &> /dev/null; then
            echo "Maven not found, installing..."
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S yum install -y maven
          else
            echo "Maven is already installed"
          fi
  check-port:
    name: "Ensure that Port 80 is not in a running state."
    runs-on: self-hosted
    needs: check-java-maven
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "List of Ports Currently in the LISTEN State"
        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -i -P -n | grep LISTEN
      - name: "Identify the process on port 80"
        id: check-port
        run: |
          if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80 | xargs -n 1 ps -o comm= -p | grep containerd > /dev/null; then
            echo "port_exist=containerd" >> $GITHUB_ENV
          elif echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80 > /dev/null; then
            echo "port_exist=process" >> $GITHUB_ENV
          fi
      - name: "Terminate processes on port 80"
        env:
          PORT_EXIST: ${{ steps.check-port.outputs.port_exist }}
        run: |
          if [ "$PORT_EXIST" = "process" ]; then
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S kill -9 $(echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lsof -t -i:80)
          elif [ "$PORT_EXIST" = "containerd" ]; then
            docker stop $(docker ps -q --filter "expose=80/tcp" --filter "status=running") 
          fi
          
  build_run:
    name: "Compile and Execute a Java Maven Dependency Project"
    runs-on: self-hosted
    needs: check-port
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Build with Maven"
        run: mvn -B package --file pom.xml
      - name: "Run the project in the background using the JVM with the command 'java -jar target/..SNAPSHOT.war'."
        run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S java -jar target/MSB-0.0.1-SNAPSHOT.war &
